services:
  db:
    image: postgres:15
    container_name: sentrigov2-db

    environment:
      POSTGRES_USER: sentrigov2
      POSTGRES_PASSWORD: sentrigov2
      POSTGRES_DB: sentrigov2

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
